<div class="pagination-container" id="paginationContainer">
    <div class="pagination-info">
        Showing <strong id="paginationStart">1</strong> to <strong id="paginationEnd">10</strong> of <strong id="paginationTotal">0</strong> entries
    </div>

    <div class="pagination-controls" id="paginationControls">
        <!-- Pagination buttons will be generated by JavaScript -->
    </div>

    <div class="pagination-select">
        <label for="itemsPerPage">Show:</label>
        <select id="itemsPerPage">
            <option value="5">5</option>
            <option value="10" selected>10</option>
            <option value="20">20</option>
            <option value="50">50</option>
            <option value="100">100</option>
        </select>
    </div>
</div>
